version: '3.8'

services:
  account:
    image: account:latest
    ports:
      - "8081:8081"
    environment:
      TZ: America/Sao_Paulo
    networks:
      - shared_network

networks:
  shared_network:
    external: true
