version: '3.8'

services:
  account:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      TZ: America/Sao_Paulo
    networks:
      - shared_network

networks:
  shared_network:
    external: true
